dbt_infosys:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dbt-cloud-XXX-dev  # name of the project in BigQuery
      dataset: dbt_google_analytics
      location : US
      threads: 4
      keyfile: ~/secrets/dbt-service-keyfile-dev.json
      timeout_seconds: 300
      priority: interactive
      retries: 1
      
    prod: # your production environment
      type: bigquery
      method: service-account
      project: dbt-cloud-XXX-prod  # name of the project in BigQuery
      dataset: dbt_google_analytics
      location : US
      threads: 4
      keyfile: /secrets/dbt-service-keyfile-prod.json
      timeout_seconds: 300
      priority: interactive
      retries: 1
